name: rebuild and push container

on:
  workflow_dispatch:
    inputs:
      containerfile:
        description: "Which container to rebuild"
        required: true
        type: choice
        options:
          - alpine-3.21-builder
          - debian-bullseye-builder

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aarnotenjin
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit timestamp and short hash
        run: |
          echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          echo "SHORTHASH=$(echo ${{ github.sha }} | cut -c1-13)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: containerfiles/${{ inputs.containerfile }}
          tags: aarnotenjin/${{ inputs.containerfile }}:rev${{ env.SHORTHASH }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
